"""Add many-to-one models

Revision ID: 1a4820b64a2a
Revises: d2595643436a
Create Date: 2026-08-18 23:16:32.180730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a4820b64a2a'
down_revision: Union[str, None] = 'd2595643436a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE matchtype ADD VALUE IF NOT EXISTS 'MANY_TO_ONE'")
    from sqlalchemy.dialects.postgresql import ENUM
    op.create_table('reconciliation_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('bank_txn_id', sa.UUID(), nullable=False),
    sa.Column('match_type', ENUM('EXACT', 'DATE_SHIFT', 'FEE_ADJUSTED', 'MANY_TO_ONE', 'UNRECONCILED', name='matchtype', create_type=False), nullable=False),
    sa.Column('total_internal_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('bank_deposit_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('fee_deducted', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('status', ENUM('MATCHED', 'UNRECONCILED', 'UNDER_REVIEW', name='resultstatus', create_type=False), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('review_metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_txn_id'], ['bank_statement.id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['reconciliation_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_groups_bank_txn_id'), 'reconciliation_groups', ['bank_txn_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_groups_batch_id'), 'reconciliation_groups', ['batch_id'], unique=False)
    op.create_table('reconciliation_group_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('internal_txn_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['reconciliation_groups.id'], ),
    sa.ForeignKeyConstraint(['internal_txn_id'], ['internal_ledger.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_group_members_group_id'), 'reconciliation_group_members', ['group_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_group_members_internal_txn_id'), 'reconciliation_group_members', ['internal_txn_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reconciliation_group_members_internal_txn_id'), table_name='reconciliation_group_members')
    op.drop_index(op.f('ix_reconciliation_group_members_group_id'), table_name='reconciliation_group_members')
    op.drop_table('reconciliation_group_members')
    op.drop_index(op.f('ix_reconciliation_groups_batch_id'), table_name='reconciliation_groups')
    op.drop_index(op.f('ix_reconciliation_groups_bank_txn_id'), table_name='reconciliation_groups')
    op.drop_table('reconciliation_groups')
    # ### end Alembic commands ###
