"""create_all_tables

Revision ID: d2595643436a
Revises: 
Create Date: 2026-08-15 22:42:45.326300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2595643436a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reconciliation_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('internal_file_key', sa.String(), nullable=False),
    sa.Column('bank_file_key', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'INGESTING', 'MATCHING', 'ML_TRIAGE', 'COMPLETE', 'FAILED', name='batchstatus'), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank_statement',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bank_reference_id', sa.String(), nullable=False),
    sa.Column('deposit_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('settlement_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'MATCHED', 'UNMATCHED', name='bankstatus'), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['reconciliation_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_statement_bank_reference_id'), 'bank_statement', ['bank_reference_id'], unique=False)
    op.create_index(op.f('ix_bank_statement_batch_id'), 'bank_statement', ['batch_id'], unique=False)
    op.create_table('batch_validation_errors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('file_type', sa.Enum('INTERNAL_LEDGER', 'BANK_STATEMENT', name='filetype'), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['reconciliation_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_validation_errors_batch_id'), 'batch_validation_errors', ['batch_id'], unique=False)
    op.create_table('internal_ledger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'MATCHED', 'UNMATCHED', name='ledgerstatus'), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['reconciliation_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internal_ledger_batch_id'), 'internal_ledger', ['batch_id'], unique=False)
    op.create_index(op.f('ix_internal_ledger_merchant_id'), 'internal_ledger', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_internal_ledger_transaction_id'), 'internal_ledger', ['transaction_id'], unique=False)
    op.create_table('reconciliation_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('internal_txn_id', sa.UUID(), nullable=True),
    sa.Column('bank_txn_id', sa.UUID(), nullable=True),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('match_type', sa.Enum('EXACT', 'DATE_SHIFT', 'FEE_ADJUSTED', 'UNRECONCILED', name='matchtype'), nullable=False),
    sa.Column('fee_deducted', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('is_anomaly', sa.Boolean(), nullable=False),
    sa.Column('anomaly_reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('MATCHED', 'UNRECONCILED', 'UNDER_REVIEW', name='resultstatus'), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_txn_id'], ['bank_statement.id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['reconciliation_batches.id'], ),
    sa.ForeignKeyConstraint(['internal_txn_id'], ['internal_ledger.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_results_batch_id'), 'reconciliation_results', ['batch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reconciliation_results_batch_id'), table_name='reconciliation_results')
    op.drop_table('reconciliation_results')
    op.drop_index(op.f('ix_internal_ledger_transaction_id'), table_name='internal_ledger')
    op.drop_index(op.f('ix_internal_ledger_merchant_id'), table_name='internal_ledger')
    op.drop_index(op.f('ix_internal_ledger_batch_id'), table_name='internal_ledger')
    op.drop_table('internal_ledger')
    op.drop_index(op.f('ix_batch_validation_errors_batch_id'), table_name='batch_validation_errors')
    op.drop_table('batch_validation_errors')
    op.drop_index(op.f('ix_bank_statement_batch_id'), table_name='bank_statement')
    op.drop_index(op.f('ix_bank_statement_bank_reference_id'), table_name='bank_statement')
    op.drop_table('bank_statement')
    op.drop_table('reconciliation_batches')
    # ### end Alembic commands ###
